// <auto-generated />
using System;
using CarrinhoCompras.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarrinhoCompras.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816012433_tabelasIniciais")]
    partial class tabelasIniciais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarrinhoCompras.Domain.Entities.Carrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CupomAplicadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CupomAplicadoId");

                    b.ToTable("Carrinhos", (string)null);
                });

            modelBuilder.Entity("CarrinhoCompras.Domain.Entities.Cupom", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    b.Property<string>("CodigoCupom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CodigoCupom");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataValidade");

                    b.Property<decimal>("PercentualDesconto")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PercentualDesconto");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCupom")
                        .IsUnique();

                    b.ToTable("Cupons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoCupom = "10OFF",
                            DataExpiracao = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            PercentualDesconto = 10m
                        },
                        new
                        {
                            Id = 2,
                            CodigoCupom = "15OFF",
                            DataExpiracao = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            PercentualDesconto = 15m
                        },
                        new
                        {
                            Id = 3,
                            CodigoCupom = "20OFF",
                            DataExpiracao = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            PercentualDesconto = 20m
                        });
                });

            modelBuilder.Entity("CarrinhoCompras.Domain.Entities.ItemCarrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarrinhoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensCarrinho", (string)null);
                });

            modelBuilder.Entity("CarrinhoCompras.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("DescricaoProduto");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecoUnitario");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("integer")
                        .HasColumnName("QuantidadeEstoque");

                    b.HasKey("Id");

                    b.ToTable("Produtos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescricaoProduto = "Mouse sem fio",
                            PrecoUnitario = 79.90m,
                            QuantidadeEstoque = 50
                        },
                        new
                        {
                            Id = 2,
                            DescricaoProduto = "Teclado mecânico",
                            PrecoUnitario = 249.90m,
                            QuantidadeEstoque = 30
                        },
                        new
                        {
                            Id = 3,
                            DescricaoProduto = "Monitor 24\" Full HD",
                            PrecoUnitario = 799.90m,
                            QuantidadeEstoque = 15
                        },
                        new
                        {
                            Id = 4,
                            DescricaoProduto = "Notebook 15\"",
                            PrecoUnitario = 3499.90m,
                            QuantidadeEstoque = 8
                        },
                        new
                        {
                            Id = 5,
                            DescricaoProduto = "Fone de ouvido Bluetooth",
                            PrecoUnitario = 199.90m,
                            QuantidadeEstoque = 40
                        },
                        new
                        {
                            Id = 6,
                            DescricaoProduto = "Webcam Full HD",
                            PrecoUnitario = 149.90m,
                            QuantidadeEstoque = 25
                        },
                        new
                        {
                            Id = 7,
                            DescricaoProduto = "Cadeira de escritório",
                            PrecoUnitario = 899.90m,
                            QuantidadeEstoque = 12
                        },
                        new
                        {
                            Id = 8,
                            DescricaoProduto = "SSD 480GB",
                            PrecoUnitario = 249.90m,
                            QuantidadeEstoque = 20
                        },
                        new
                        {
                            Id = 9,
                            DescricaoProduto = "Carregador USB-C 65W",
                            PrecoUnitario = 89.90m,
                            QuantidadeEstoque = 60
                        },
                        new
                        {
                            Id = 10,
                            DescricaoProduto = "Mochila para notebook",
                            PrecoUnitario = 129.90m,
                            QuantidadeEstoque = 35
                        });
                });

            modelBuilder.Entity("CarrinhoCompras.Domain.Entities.Carrinho", b =>
                {
                    b.HasOne("CarrinhoCompras.Domain.Entities.Cupom", "CupomAplicado")
                        .WithMany()
                        .HasForeignKey("CupomAplicadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CupomAplicado");
                });

            modelBuilder.Entity("CarrinhoCompras.Domain.Entities.ItemCarrinho", b =>
                {
                    b.HasOne("CarrinhoCompras.Domain.Entities.Carrinho", null)
                        .WithMany("Itens")
                        .HasForeignKey("CarrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarrinhoCompras.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("CarrinhoCompras.Domain.Entities.Carrinho", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
